name: omify_mobile
description: "Omify Mobile App - Exact copy of web version"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  feather_icons: ^1.2.0
  line_icons: ^2.0.3
  font_awesome_flutter: ^10.7.0
  ionicons: ^0.2.2
  tabler_icons_flutter: ^2.11.0
  eva_icons_flutter: ^3.1.0
  go_router: ^13.0.0
  mysql_client: ^0.0.20
  uuid: ^4.3.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
